# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ebd330fa9f73038573d5002688ba04f54af4da2526587d87f61670bf9f9a09bff0d7b787e9da5589cf96b827dc5d2c9f78ffde87b1e3fa0e39e54015a14b90f

test:
  secret_key_base: 9b04acf7561d25a64f3f723a2396e817420a05e56ac0be880c02b9eaa7bc574a4dbac72d2c8ff5604b890928b8e0881266de93217d1f55846f8c8bd3ab3de203

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
